In [20]:
import numpy as np

In [21]:
d=np.arange(1000000)

In [22]:
%time for i in range(1,10): r=d*2

Wall time: 45.5 ms


In [33]:
a = np.arange(12).reshape(3, 4)

In [34]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
a.size

12

In [36]:
a.shape

(3, 4)

In [37]:
a.ndim

2

In [38]:
a.dtype.name


'int32'

In [39]:
a.itemsize

4

In [40]:
type(a)


numpy.ndarray

In [41]:
b = np.array([6, 7, 8])

In [42]:
b

array([6, 7, 8])

In [43]:
type(b)


numpy.ndarray

In [44]:
a.dtype

dtype('int32')

In [45]:
b.dtype

dtype('int32')

In [46]:
np.linspace( 0, 2, 9 )   

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [48]:
A = np.array( [[1,1],
               [0,1]] )


In [49]:
B = np.array( [[2,0],
               [3,4]] )

In [50]:
A * B 

array([[2, 0],
       [0, 4]])

In [51]:
A @ B 

array([[5, 4],
       [3, 4]])

In [52]:
A.dot(B)  

array([[5, 4],
       [3, 4]])

In [54]:
a.sum()

66

In [55]:
a.min()

0

In [56]:
a.max()

11

In [59]:
S = np.arange(5)

In [60]:
S

array([0, 1, 2, 3, 4])

In [68]:
a.ravel

<function ndarray.ravel>

In [4]:
import numpy as np

In [8]:
S=[1,2,3,4,5]

In [9]:
np.add(S, 2)

array([3, 4, 5, 6, 7])

In [10]:
np.subtract(S,1)

array([0, 1, 2, 3, 4])

In [11]:
np.multiply(S,5)

array([ 5, 10, 15, 20, 25])

In [12]:
np.power(S,2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [14]:
np.absolute(S)

array([1, 2, 3, 4, 5])

In [15]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [20]:
x = np.array([1,2,3,4,5,6])
avg = x.mean()
print(avg)

3.5


In [21]:
sum = x.sum()
print(sum)

21


In [24]:
sx = np.sin(x)        
print(sx)

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


In [2]:
import numpy as np


In [3]:
a = np.array([1, 2, 3], dtype = complex) 
print (a)

[1.+0.j 2.+0.j 3.+0.j]


In [4]:
bool_arr = np.array([1, 0.5, 0, None, 'a', '', True, False], dtype=bool)
print(bool_arr)

[ True  True False False  True False  True False]


In [5]:
a=np.linspace(1,3,10)
print(a)

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


In [6]:
a=np.array([(1,2,3),(3,4,5,)])
print(np.sqrt(a))

[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]


In [7]:
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x-y)

[[0 0 0]
 [0 0 0]]


In [8]:
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x*y)

[[ 1  4  9]
 [ 9 16 25]]


In [9]:
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x/y)

[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(np.vstack((x,y)))

[[1 2 3]
 [3 4 5]
 [1 2 3]
 [3 4 5]]


In [11]:
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(np.hstack((x,y)))

[[1 2 3 1 2 3]
 [3 4 5 3 4 5]]


In [12]:
x= np.array([(1,2,3),(3,4,5)])
print(x.ravel())

[1 2 3 3 4 5]


In [13]:
array1d = np.zeros(3)
print(array1d)

[0. 0. 0.]


In [14]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
print(np.diag(np.arange(0, 8, 2)))

[[0 0 0 0]
 [0 2 0 0]
 [0 0 4 0]
 [0 0 0 6]]


In [16]:
array1d = np.array([1, 2, 3, 4, 5, 6])
print(array1d[0])   # Get first value
print(array1d[-1])  # Get last value
print(array1d[3])   # Get 4th value from first
print(array1d[-5])  # Get 5th value from last

1
6
4
2


In [17]:
array1 = np.array([[10, 20, 30], [40, 50, 60]])
array2 = np.array([[2, 3, 4], [4, 6, 8]])
array3 = np.array([[-2, 3.5, -4], [4.05, -6, 8]])
print(np.add(array1, array2))

[[12 23 34]
 [44 56 68]]


In [18]:
print("Sum: ", np.sum(array1))

Sum:  210


In [19]:
print("Prod: ", np.prod(array1))

Prod:  720000000


In [20]:
print("Var: ", np.var(array1))

Var:  291.6666666666667


In [21]:
arrayA = np.append(array1, array2, axis=0)
print(arrayA)

[[10 20 30]
 [40 50 60]
 [ 2  3  4]
 [ 4  6  8]]


In [22]:
arrayC = np.concatenate((array1, array2))
print(arrayC)

[[10 20 30]
 [40 50 60]
 [ 2  3  4]
 [ 4  6  8]]
